new icons
zepdev/zeppelin-element-library pull request #167
Opened 2020-12-01 16:04 UTC by cabutler10

2020-12-07 16:50 UTC, byjs-dev commented on .eslintcache
> +[{"/Users/alyssabutler/Documents/ZLab/zeppelin-element-library/src/index.js":"1","/Users/alyssabutler/Documents/ZLab/zeppelin-element-library/src/elements/button/ButtonPage.jsx":"2","/Users/alyssabut
Please put that into .gitignore and remove it from the PR. ;)

2020-12-07 17:00 UTC, byjs-dev requested changes
Could you please use "-" instead of "_" in the icon-/file name? Unless our CoP proposed solution changed. Sorry and thank you.

2020-12-08 13:45 UTC, cabutler10 commented
@byjs-dev i didn't notice, dashes have been updated!

2020-12-09 08:32 UTC, byjs-dev approved these changes
Thank you. Please just remove the .eslintchache and add it to the .gitignore file before merging. 
As next step I'd like to have the creation of the svg spritesheet automated and also an optimization for the svgs. We could use something like https://github.com/edenspiekermann/sprite.sh and https://github.com/svg/svgo for that. What do you think?

2020-12-09 08:52 UTC, cabutler10 commented
@byjs-dev i never use svg sprites so am super happy to have your expertise here. Would you be willing to take one the work to change the sprites?

2020-12-09 08:55 UTC, byjs-dev commented
> @byjs-dev i never use svg sprites so am super happy to have your expertise here. Would you be willing to take one the work to change the sprites?

Sure, I'll add an issue with this topic.

2020-12-14 10:10 UTC, merged

2020-12-18 11:06 UTC, byjs-dev commented
:tada: This PR is included in version 3.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/zeppelin-element-library/v/3.0.0)
- [GitHub release](https://github.com/zepdev/zeppelin-element-library/releases/tag/v3.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: